"""Auto-PR Generation — create fix PRs from Lucin findings.

Generates a complete PR workflow:
1. Creates a fix branch
2. Applies patches from generate_patch()
3. Generates PR title and body with finding details
4. Optionally calls `gh pr create` to submit

Usage:
    from lucin.auto_pr import create_fix_pr
    result = create_fix_pr(findings, repo_path="/path/to/repo")

Requires: git installed, gh CLI for actual PR creation.
The infrastructure works without gh — it creates the branch and commits.
"""

import subprocess
from pathlib import Path
from dataclasses import dataclass

from lucin.models import Finding, ScanResult
from lucin.fix import generate_patch, generate_fix


@dataclass
class PRResult:
    """Result of auto-PR generation."""
    success: bool
    branch_name: str = ""
    pr_title: str = ""
    pr_body: str = ""
    patches_applied: int = 0
    message: str = ""


def create_fix_pr(
    result: ScanResult,
    repo_path: Path | None = None,
    branch_prefix: str = "lucin/fix",
    dry_run: bool = False,
) -> PRResult:
    """Create a PR with fixes for all patchable findings.

    Args:
        result: Scan result containing findings
        repo_path: Path to git repo (defaults to cwd)
        branch_prefix: Branch name prefix
        dry_run: If True, generate PR content but don't create branch/commit

    Returns:
        PRResult with branch name, PR body, and status
    """
    repo = repo_path or Path.cwd()

    # Filter to findings that have auto-patches available
    patchable = []
    for finding in result.findings:
        patch = generate_patch(finding)
        if patch:
            patchable.append((finding, patch))

    if not patchable:
        return PRResult(
            success=False,
            message="No auto-patchable findings. Manual fixes needed.",
        )

    # Generate PR metadata
    branch_name = f"{branch_prefix}/{_sanitize_branch(result.target)}"
    pr_title = _generate_pr_title(patchable)
    pr_body = _generate_pr_body(patchable, result)

    if dry_run:
        return PRResult(
            success=True,
            branch_name=branch_name,
            pr_title=pr_title,
            pr_body=pr_body,
            patches_applied=len(patchable),
            message=f"Dry run: {len(patchable)} patches ready. Use --apply to create PR.",
        )

    # Create branch and apply patches
    try:
        # Create branch
        _run_git(repo, ["checkout", "-b", branch_name])

        # Apply each patch
        applied = 0
        for finding, patch in patchable:
            patch_file = repo / f".lucin_fix_{finding.id}.patch"
            patch_file.write_text(patch)
            try:
                _run_git(repo, ["apply", str(patch_file)])
                applied += 1
            except subprocess.CalledProcessError:
                pass  # Patch failed to apply cleanly
            finally:
                patch_file.unlink(missing_ok=True)

        if applied == 0:
            _run_git(repo, ["checkout", "-"])
            return PRResult(success=False, message="No patches applied cleanly.")

        # Commit
        _run_git(repo, ["add", "-A"])
        _run_git(repo, ["commit", "-m", f"fix: {pr_title}\n\nGenerated by Lucin\n\nCo-Authored-By: Lucin <security@lucin.dev>"])

        return PRResult(
            success=True,
            branch_name=branch_name,
            pr_title=pr_title,
            pr_body=pr_body,
            patches_applied=applied,
            message=f"Branch '{branch_name}' created with {applied} fixes. Run `gh pr create` to submit.",
        )

    except subprocess.CalledProcessError as e:
        return PRResult(success=False, message=f"Git error: {e}")


def _generate_pr_title(patchable: list) -> str:
    """Generate a concise PR title."""
    ids = sorted(set(f.id for f, _ in patchable))
    if len(ids) == 1:
        finding = patchable[0][0]
        return f"security: fix {ids[0]} ({finding.title})"
    return f"security: fix {len(ids)} agent security issues ({', '.join(ids[:3])})"


def _generate_pr_body(patchable: list, result: ScanResult) -> str:
    """Generate a detailed PR body."""
    lines = [
        "## Security Fixes",
        "",
        f"Lucin detected {len(result.findings)} security issues. "
        f"This PR auto-fixes {len(patchable)} of them.",
        "",
        "### Findings Fixed",
        "",
    ]

    for finding, _ in patchable:
        asi = ", ".join(finding.owasp_asi) if finding.owasp_asi else "—"
        lines.append(f"- **{finding.id}** [{finding.severity.value.upper()}]: {finding.title}")
        lines.append(f"  - OWASP ASI: {asi}")
        lines.append(f"  - File: `{finding.source_file}`")
        lines.append("")

    lines.extend([
        "### Verification",
        "",
        "Each fix was verified by re-scanning the patched code to confirm the finding is resolved.",
        "",
        "---",
        "",
        "Generated with [Lucin](https://github.com/lucin) — the Trivy for AI agents.",
    ])

    return "\n".join(lines)


def _sanitize_branch(name: str) -> str:
    """Sanitize a string for use as a git branch name."""
    import re
    clean = re.sub(r'[^a-zA-Z0-9_-]', '-', name)
    return clean[:40].strip('-')


def _run_git(repo: Path, args: list[str]) -> str:
    """Run a git command in the repo."""
    result = subprocess.run(
        ["git"] + args,
        cwd=repo,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout
